[[assertj-core-extensions]]
=== Extending assertions

AssertJ can be extends by Condition or writing your own assertions class.

[[assertj-core-conditions]]
==== Conditions

Assertions can be extended by using conditions, to create a condition you just have to implement https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/Condition.html[`org.assertj.assertions.core.Condition`] and its unique method matches.

Once your Condition is created, you can use it with methods : `is(myCondition)` or `has(myCondition)`, both verifying that the condition is met (hint: pick the one that makes your code more readable).

Example:
[source,java]
----
// jedi is a Condition
assertThat("Yoda").is(jedi);
----

Conditions can be combined with :

* `not(Condition)`: given condition must not be met
* `allOf(Condition...)`: all given conditions must be met
* `anyOf(Condition...)`: one of the given conditions must be met

You can verify that a Condition is met on elements of a collection, with the following methods:

* `are(condition)`/`have(condition)`: all elements must meet the given condition
* `areAtLeast(n, condition)`/`haveAtLeast(n, condition)`: at least n elements must meet the given condition
* `areAtMost(n, condition)`/`haveAtMost(n, condition)`: no more than n elements must meet the given condition
* `areExactly(n, condition)`/`haveExactly(n, condition)`: exactly n elements must meet the given condition

Moreover all Condition related methods have their negation counterpart, `is`/`isNot`, `have`/`doesNotHave`, `are`/`areNot`, ...

The examples below are from https://github.com/assertj/assertj-examples/[assertj-examples] and more specifically https://github.com/assertj/assertj-examples/blob/main/assertions-examples/src/test/java/org/assertj/examples/condition/UsingConditionExamples.java[UsingConditionExamples.java].

[[assertj-core-condition-creation]]
===== Creating a Condition

Let's define two similar conditions: `jedi` and `jediPower` with the same implementation to show that code readability is better when using `jedi` with `is` and jediPower with `has`.

[source,java]
----
import static org.assertj.core.util.Sets.newLinkedHashSet;

static Set<String> JEDIS = newLinkedHashSet("Luke", "Yoda", "Obiwan");

// implementation with Java 8 lambda
Condition<String> jediPower = new Condition<>(JEDIS::contains, "jedi power"); 

// implementation with Java 7
Condition<String> jedi = new Condition<String>("jedi") {
  @Override
  public boolean matches(String value) {
    return JEDIS.contains(value);
  }
};
----

The String parameter is describing the condition, this is used in error messages.


[[assertj-core-condition-usage]]
===== Using Conditions

Usage with single instances:
[source,java]
----
assertThat("Yoda").is(jedi);
assertThat("Vader").isNot(jedi);

assertThat("Yoda").has(jediPower);
assertThat("Solo").doesNotHave(jediPower);
----

The Condition description is used in error messages, ex:
[source,java]
----
assertThat("Vader").is(jedi);
----
will fail with the following error message:
[source,text]
----
"expecting:<'Vader'> to be:<jedi>"
----



Usage with collections:

[source,java]
----
assertThat(list("Luke", "Yoda")).are(jedi);
assertThat(list("Leia", "Solo")).areNot(jedi);

assertThat(list("Luke", "Yoda")).have(jediPower);
assertThat(list("Leia", "Solo")).doNotHave(jediPower);

assertThat(list("Luke", "Yoda", "Leia")).areAtLeast(2, jedi);
assertThat(list("Luke", "Yoda", "Leia")).haveAtLeast(2, jediPower);

assertThat(list("Luke", "Yoda", "Leia")).areAtMost(2, jedi);
assertThat(list("Luke", "Yoda", "Leia")).haveAtMost(2, jediPower);

assertThat(list("Luke", "Yoda", "Leia")).areExactly(2, jedi);
assertThat(list("Luke", "Yoda", "Leia")).haveExactly(2, jediPower);
----

[[assertj-core-combining-condition]]
===== Combining Conditions

Conditions can be combined with `allOf(Condition...)` (logical and) or `anyOf(Condition...)` (logical or), `not` can be used to invert one.

Let's define a sith condition:
[source,java]
----
List<String> SITHS = list("Sidious", "Vader", "Plagueis");
Condition<String> sith = new Condition<>(SITHS::contains, "sith"); 
----

We can write these assertions:
[source,java]
----
assertThat("Vader").is(anyOf(jedi, sith));
assertThat("Solo").is(allOf(not(jedi), not(sith)));
----


[[assertj-core-custom-assertions]]
==== Custom Assertions (TODO)

TODO
