[[release-notes]]
=== Release Notes

NOTE: AssertJ Guava main documentation is still in http://joel-costigliola.github.io/assertj/assertj-guava.html until it is moved to this website. +
The new release notes though will be published here.

Latest release notes:

- link:#assertj-guava-3-3-0-release-notes[AssertJ Guava 3.3.0]
- older release notes are in the http://joel-costigliola.github.io/assertj/assertj-guava.html#latest-release[old site].

The javadoc for this release can be found here: https://www.javadoc.io/doc/org.assertj/assertj-guava/3.3.0/index.html

[[assertj-guava-3-3-0-release-notes]]
==== AssertJ Guava 3.3.0

Release date : 2019-11-09

[[assertj-guava-3.3.0-contributors]]
[.release-note-category]#icon:user[] Contributors#

Thanks to chrisly42 and Stefano Cordio for their contributions!

[[assertj-guava-3.3.0-new-features]]
[.release-note-category]#icon:plus-circle[] New features#

- Add link:#assertj-guava-3.3.0-InstanceOfAssertFactories[`InstanceOfAssertFactories`] to chain specific type assertions. (Stefano Cordio)

[[assertj-guava-3.3.0-improvements]]
[.release-note-category]#icon:arrow-circle-up[] Improvements#

- AssertJ's javadoc are now searchable.
- Use beautiful AssertJ's site code style for javadoc :)
- Migrate to JUnit 5 and latest assertj-core version 3.14.0.

[[assertj-guava-3.3.0-fixed]]
[.release-note-category]#icon:wrench[] Fixed#

- Fix for `OptionalAssert.contains()` that was not working for primitive arrays. (chrisly42)

[[assertj-guava-3.3.0-deprecated]]
[.release-note-category]#icon:ban[] Deprecated#

- Deprecate `org.assertj.guava.data.MapEntry` for `org.assertj.core.data.MapEntry`

[[assertj-guava-3.3.0-InstanceOfAssertFactories]]
[.release-note-item]#Add `InstanceOfAssertFactories` to allow chain specific type assertions#

Add factories for `ByteSource`, `Multimap`, `Multiset`, `Optional` (guava) and `Table` to allow to chain specific type assertions from a value initially declared as a less specific type.

Let's start with the problem `asInstanceOf` is solving: in the following example we would like to call `Table` assertions but this is not possible since `value` is declared as an `Object` thus only `Object` assertions are accessible.
[source,java,indent=0]
----
// Given a Table declared as an Object
Object actual = HashBasedTable.<Integer, Integer, String> create();

// We would like to call Table assertions but this is not possible since value is declared as an Object
assertThat(actual).isEmpty(); // this does not compile !
----

Thanks to `asInstanceOf` we can now tell AssertJ to consider `value` as a `Table` in order to call `Table` assertions. +
To do so we need to pass an `InstanceOfAssertFactory` that can build a `TableAssert`, fortunately you don't have to write it, it is already available in `InstanceOfAssertFactories`!

[source,java,indent=0]
----
// Given a Table declared as an Object
Object actual = HashBasedTable.<Integer, Integer, String> create();

// With asInstanceOf, we switch to specific Table assertion by specifying the InstanceOfAssertFactory for Table
assertThat(value).asInstanceOf(InstanceOfAssertFactories.TABLE)
                 .isEmpty();
----

AssertJ verifies that the actual value is compatible with the assertions `InstanceOfAssertFactory` is going to give access to.

`InstanceOfAssertFactories` provides static factories for all types AssertJ provides assertions for, additional factories can be created with custom `InstanceOfAssertFactory` instances.

