[[user-guide]]
= AssertJ User Guide

This is now the official site for AssertJ Core replacing: http://joel-costigliola.github.io/assertj/assertj-core.html

The migration from the old site is still in progress but this new site already contains useful information and even some not documented previously!

If you feel something is missing or not clear enought, please raise an issue in https://github.com/assertj/doc/issues or even better contribute to it!

:imagesdir: images
:imagesoutdir: {outdir}/user-guide/images
//
ifdef::backend-pdf[:imagesdir: {imagesoutdir}]
//
:sectnums:
//

include::../link-attributes.adoc[]

include::overview.adoc[]

include::assertions-guide.adoc[]

include::contributors.adoc[]

[[release-notes]]
== Release Notes

=== AssertJ Core

==== AssertJ Core 3.12.2 Release notes

The main issue fixed was to ignore static methods when finding property accessors (contributed by Andy Wilkinson) which could break some tests since bare name method introspection was introduced in 3.12.0.

`anySatisfy` for `Maps` was improved and does not continue evaluating elements once a match is found (contributed by Erhard Pointl).

==== AssertJ Core 3.12.1 Release notes

Fix a regression that included a bad module-info.class (thanks Jaro Kuruc) and other minor improvements.

==== AssertJ Core 3.12.0 Release notes

Release date : 2019-02-14

The main feature of this release is a beta version of the link:#assertj-core-recursive-comparison[new Recursive comparison API]!
It covers what `isEqualToComparingFieldByFieldRecursively` used but easier to use and with more capabilities.

It is a Beta version because we want to have feedback from the community to make it even better before freezing the API.
There are more capabilities to come in the next releases, stay tuned!

===== Contributors

Big thanks for all the contributors to this release:

Pascal Schumacher, Erhard Pointl, Vladimir Chernikov, Sandra Parsick, Martin Tarjanyi, Stephan Windmüller, Yaroslav Mitsynskiy, Thomas Traude, Georg Berky, Tomek Kaczanowski, Lukáš Křečan, Yoann Rodière, Filip Hrisafov, Steven Schlansker, Jeremy Landis, Jack Gough, Sebastian Kempken, Stefan Mandel, Alexandre de Champeaux, Arvid Heise, Jeff Walker, Dmitrii Priporov and Joshua Kitchen.

[[assertj-core-3.12.0-breaking-changes]]
===== Breaking changes

- Introduce first class `Iterator` assertions (Stephan Windmüller).

WARNING: This removes the previously supported "`Iterable`" assertions (like `containsOnly`), call http://joel-costigliola.github.io/assertj/core-8/api/org/assertj/core/api/AbstractIteratorAssert.html#toIterable--[`IteratorAssert#toIterable`] to access them again, ex:

[source,java,indent=0]
----
Iterator<String> bestBasketBallPlayers = getBestBasketBallPlayers();

assertThat(bestBasketBallPlayers).toIterable().contains("Jordan", "Magic", "Lebron");
----

- Add configurable support for bare-named property introspection. (Steven Schlansker)

AssertJ uses introspection in various places, one example is extracting properties as in `extracting("name")`. AssertJ is able to get values with getters like `getName()`, with this improvement it now can get property values with bare name method like `name()`.

WARNING: Bare-named property introspection is enabled by default and thus changes AssertJ behavior which can break some existing tests relying on introspection, this is especially true as AssertJ wrongly tries static methods (https://github.com/joel-costigliola/assertj-core/issues/1458 had been created to address that).

It is possible to avoid this probem by calling `Assertions.setExtractBareNamePropertyMethods(false);` before every impacted tests.

This is a bit tedious but an improvement is planned in the next release to provide a place to perform global configuration with the same mechanism allowing to link:#assertj-core-custom-representation-default-global-scope[register a custom representation].


===== New features

- New Recursive comparison API! (Beta version)
- Add `satisfiesAnyOf` base assertion. TODO document
- Add `isAbstract` to `Class` assertions. (Erhard Pointl)
- Add `hasValueCloseTo(percentage)` to `OptionalDouble` assertion. (Joshua Kitchen)
- Add `hasOnlyOneElementSatisfying(Consumer)` to `AtomicReferenceArray` assertions. (Vladimir Chernikov)
- Add `hasAllNullFieldsOrProperties` and `hasAllNullFieldsOrPropertiesExcept`. (Vladimir Chernikov)
- Add `hasSizeGreaterThan`, `hasSizeLessThanOrEqualTo`, `hasSizeGreaterThanOrEqualTo` and `hasSizeGreaterThan` to `CharSequence` and `String` assertions. (Sandra Parsick)
- Add `hasSizeGreaterThan`, `hasSizeLessThanOrEqualTo`, `hasSizeGreaterThanOrEqualTo`, `hasSizeGreaterThan` and `hasSizeBetween` to object and primitives array, `Iterable` and `Map`. (Martin Tarjanyi)
- Add `hasSizeBetween` to `CharSequence` and `String` assertions. (Martin Tarjanyi)
- Add `noneSatisfy(BiConsumer)` to `Map` assertions. (Erhard Pointl)
- Add `containsExactlyEntriesOf` assertion to check that a `Map` contains exactly all entries of another `Map`. (Filip Hrisafov)
- Add `containsOnlyKeys(Iterable keys)` to `Map` assertion. (Sebastian Kempken)
- Add `anySatifies(BiConsumer)` to `Map` assertion. (Stefan Mandel)
- Add `hasMessageNotContaining` to `Throwable` assertions. (Georg Berky and Sandra Parsick)
- Add `shouldHaveRootCause` to `Throwable` assertions to check the content of a root cause. (Jack Gough)
- Add `isEqualTo(String string, Objects... param)` to `String` assertion. (Dmitrii Priporov)
- Add `assertThatObject`/`thenObject` to force Object assertion. (Arvid Heise)
- Add JUnit5 to AssertJ assertions migration script for osx. (Tomek Kaczanowski)

===== Improvements

- Add stack trace of original exception to `catchThrowableOfType`. (Sam Smyth)
- `anySatisfy` and `noneSatisfy` now reports all failing elements. (Erhard Pointl)
- `ElementsShouldSatisfy` now uses the configured `Representation` to format objects.
- `ZipSatisfyError` now uses the configured `Representation` to format objects. (Jeff Walker)
- AssertJ `Double` and `Float` comparators now support `Infinity`. (Alexandre de Champeaux)
- Throw `AssertionFailedError` instead of `AssertionError` in some `String` assertions to allow IDEs to show `actual` vs `expected` visual differences. (Yaroslav Mitsynskiy)
- `Optional` `hasValue`/`contains` assertions throws `AssertionFailedError` to allow IDEs to show `actual` vs `expected` visual differences.
- Annotate `Assertions` and `Assumptions` classes with `@CheckReturnValue` and annotate methods to exclude from checking with `@CanIgnoreReturnValue`. (Pascal Schumacher)
- The error message of `allSatisfy(BiConsumer)` `Map` assertion now reports all failing entries instead of the first one. (Stefan Mandel)
- Add missing `@Since` annotations. (Erhard Pointl)
- Get rid of `Arguments` usage when possible in unit tests. (Erhard Pointl)
- Unit tests code cleanup and better use of JUnit 5. (Erhard Pointl, Pascal Schumacher and Jack Gough)
- Update to JUnit 5.4.0. (Erhard Pointl)
- Update to opentest4j to 1.1.1. (Erhard Pointl)
- Update to Byte Buddy 1.9.10. (Pascal Schumacher)
- Update Maven version to and the Maven wrapper. (Thomas Traude, Jeremy Landis)
- Do not proxy `useComparator` method in soft assertions. (Lukáš Křečan)
- Fix an NPE in `ObjectArrays#assertHasOnlyElementsOfType`. (Yoann Rodière)
- Deprecate `Extractor` in favor of `java.util.function.Function`. (Filip Hrisafov)

===== Fixed

- Use `@CanIgnoreReturnValue` on `Assertions` `fail*` methods to revert the effect of the default `@CheckReturnValue` annotation. (Erhard Pointl)
- Fix `ElementsShouldSatisfy` that failed to handle objects whose string representation contained `%`.
- Fix `ElementsShouldZipSatisfy` that failed to handle objects whose string representation contained `%`. (Arvid Heise)
