[[overview]]
== Overview

The goal of this document is to provide comprehensive reference documentation for
programmers writing tests, extension authors, and engine authors as well as build tool
and IDE vendors.

ifdef::backend-html5[This document is also available as a link:index.pdf[PDF download].]

[TIP]
.Translations
====
This document is also available in http://sjyuan.cc/junit5/user-guide-cn[Simplified Chinese]
and https://udzuki.jp/public/junit5-user-guide-ja[Japanese].
====

[[overview-what-is-junit-5]]
=== What is JUnit 5?

Unlike previous versions of JUnit, JUnit 5 is composed of several different modules from
three different sub-projects.

**JUnit Vintage** provides a `TestEngine` for running JUnit 3 and JUnit 4 based tests on
the platform.

[[overview-java-versions]]
=== Supported Java Versions

JUnit 5 requires Java 8 (or higher) at runtime. However, you can still test code that
has been compiled with previous versions of the JDK.


[[overview-getting-help]]
=== Getting Help

Ask JUnit 5 related questions on {StackOverflow} or chat with us on {Gitter}.

[[installation]]
== Installation

Artifacts for final releases and milestones are deployed to Maven Central.

Snapshot artifacts are deployed to Sonatype's {snapshot-repo}[snapshots repository] under
{snapshot-repo}/org/junit/[/org/junit].

[[dependency-metadata]]
=== Dependency Metadata


[[dependency-metadata-dependencies]]
==== Dependencies

In addition, most of the above artifacts have a direct or transitive dependency to the
following _OpenTest4J_ JAR.

* *Group ID*: `org.opentest4j`
* *Artifact ID*: `opentest4j`
* *Version*: `{ota4j-version}`


[[dependency-metadata-junit-jupiter-samples]]
=== JUnit Jupiter Sample Projects

The {junit5-samples-repo}[`junit5-samples`] repository hosts a collection of sample
projects based on JUnit Jupiter and JUnit Vintage. You'll find the respective
`build.gradle` and `pom.xml` in the projects below.

* For Gradle, check out the `{junit5-jupiter-starter-gradle}` project.
* For Maven, check out the `{junit5-jupiter-starter-maven}` project.
